第5回のたたき
teckup-tokyo/MokuMoku pull request #64
Opened 2019-11-10 07:23 UTC by yumechi

2019-11-10 11:40 UTC, Ushinji commented
作成ありがとうございました！
タイムスケジュールに休憩時間が抜けていたので追加しました。また、そもそもテンプレート自体に休憩時間がなかったので、テンプレートにも修正を行いました！

2019-11-10 12:42 UTC, yumechi commented
助かります :pray:

2019-11-11 06:23 UTC, tamanobi requested changes

2019-11-11 06:23 UTC, tamanobi commented on mokumoku#5/connpass.md
> +【住所】東京都渋谷区千駄ケ谷４丁目２３−５ ＪＰＲ千駄ヶ谷ビル 6F</br>
```suggestion
【住所】東京都渋谷区千駄ケ谷４丁目２３−５ ＪＰＲ千駄ヶ谷ビル 5F</br>
```

2019-11-11 06:23 UTC, tamanobi commented on mokumoku#5/connpass.md
> +無料 (**※懇親会は実費です**)
```suggestion
無料 (**※懇親会は自費です**)
```

2019-11-11 06:23 UTC, tamanobi commented on mokumoku#5/connpass.md
> +【住所】東京都渋谷区千駄ケ谷４丁目２３−５ ＪＰＲ千駄ヶ谷ビル 6F</br>
5Fでも6Fでもどちらでもいいけど、広いところでやりたいなら5F。

2019-11-12 01:25 UTC, tamanobi commented on mokumoku#5/connpass.md
> +無料 (**※懇親会は実費です**)
TeckUp 側ではお金を出さないはず。

2019-11-12 01:26 UTC, tamanobi commented on mokumoku#5/remind.md
> +【住所】東京都渋谷区千駄ケ谷４丁目２３−５ ＪＰＲ千駄ヶ谷ビル 6F
ここも 5Fなのか、6Fなのか決定したい。 5Fだとプロジェクターが使える。

2019-11-12 01:31 UTC, tamanobi commented on mokumoku#5/connpass.md
> +【住所】東京都渋谷区千駄ケ谷４丁目２３−５ ＪＰＲ千駄ヶ谷ビル 6F</br>
5Fだとプロジェクターが使える

2019-11-12 01:33 UTC, tamanobi commented on mokumoku#5/connpass.md
> +
この辺に飲食の注意書きを入れてほしいです。

以下、文例。

もくもくと作業できるエリアと、飲食できるエリアが分かれています。
飲食は、当日の案内に従って休憩エリアで行ってください。

2019-11-12 02:26 UTC, yumechi commented on mokumoku#5/connpass.md
> +無料 (**※懇親会は実費です**)
合ってるのでとりいれます

2019-11-12 02:26 UTC, yumechi commented on mokumoku#5/connpass.md
> +【住所】東京都渋谷区千駄ケ谷４丁目２３−５ ＪＰＲ千駄ヶ谷ビル 6F</br>
5Fにしましょう

2019-11-12 02:26 UTC, yumechi commented on mokumoku#5/remind.md
> +【住所】東京都渋谷区千駄ケ谷４丁目２３−５ ＪＰＲ千駄ヶ谷ビル 6F
5Fにしましょう

2019-11-12 02:27 UTC, yumechi commented on mokumoku#5/connpass.md
> +
それで行きましょう（当日案内用のスライドなりも必要そうですね）

2019-11-13 14:33 UTC, yumechi commented
（実費→自費はそもそもテンプレが間違ってそうなので、ついでに直します…）

2019-11-13 14:41 UTC, yumechi commented on mokumoku#5/connpass.md
> +
会場注意、という形で入れています

2019-11-13 14:42 UTC, yumechi commented on mokumoku#5/remind.md
> +【住所】東京都渋谷区千駄ケ谷４丁目２３−５ ＪＰＲ千駄ヶ谷ビル 6F
5Fにしました

2019-11-19 13:01 UTC, yumechi commented
放置されると残り続けるので一旦これマージします。必要になったら文面を直す方式で。

2019-11-19 13:01 UTC, merged